// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"github.com/flyskea/lightalk-user/rpc/internal/logic"
	"github.com/flyskea/lightalk-user/rpc/internal/svc"
	"github.com/flyskea/lightalk-user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *user.RegisterReq) (*user.UserResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *user.LoginReq) (*user.UserDetail, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) GetUser(ctx context.Context, in *user.IDReq) (*user.UserDetail, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServer) ListUser(ctx context.Context, in *user.PageReq) (*user.UserListResp, error) {
	l := logic.NewListUserLogic(ctx, s.svcCtx)
	return l.ListUser(in)
}

func (s *UserServer) CreateUserInfo(ctx context.Context, in *user.UserInfo) (*user.UserInfo, error) {
	l := logic.NewCreateUserInfoLogic(ctx, s.svcCtx)
	return l.CreateUserInfo(in)
}

func (s *UserServer) GetUserInfo(ctx context.Context, in *user.IDReq) (*user.UserInfo, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}
