// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/flyskea/lightalk-user/model/ent/schema"
	"github.com/flyskea/lightalk-user/model/ent/user"
	"github.com/flyskea/lightalk-user/model/ent/userinfo"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	userinfoMixin := schema.UserInfo{}.Mixin()
	userinfoMixinFields0 := userinfoMixin[0].Fields()
	_ = userinfoMixinFields0
	userinfoFields := schema.UserInfo{}.Fields()
	_ = userinfoFields
	// userinfoDescCreatedAt is the schema descriptor for created_at field.
	userinfoDescCreatedAt := userinfoMixinFields0[0].Descriptor()
	// userinfo.DefaultCreatedAt holds the default value on creation for the created_at field.
	userinfo.DefaultCreatedAt = userinfoDescCreatedAt.Default.(func() time.Time)
	// userinfoDescUpdatedAt is the schema descriptor for updated_at field.
	userinfoDescUpdatedAt := userinfoMixinFields0[1].Descriptor()
	// userinfo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userinfo.DefaultUpdatedAt = userinfoDescUpdatedAt.Default.(func() time.Time)
	// userinfo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userinfo.UpdateDefaultUpdatedAt = userinfoDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userinfoDescSex is the schema descriptor for sex field.
	userinfoDescSex := userinfoFields[2].Descriptor()
	// userinfo.DefaultSex holds the default value on creation for the sex field.
	userinfo.DefaultSex = userinfoDescSex.Default.(int8)
}
