// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flyskea/lightalk-user/model/ent/predicate"
	"github.com/flyskea/lightalk-user/model/ent/userinfo"
)

// UserInfoQuery is the builder for querying UserInfo entities.
type UserInfoQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserInfo
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserInfoQuery builder.
func (uiq *UserInfoQuery) Where(ps ...predicate.UserInfo) *UserInfoQuery {
	uiq.predicates = append(uiq.predicates, ps...)
	return uiq
}

// Limit adds a limit step to the query.
func (uiq *UserInfoQuery) Limit(limit int) *UserInfoQuery {
	uiq.limit = &limit
	return uiq
}

// Offset adds an offset step to the query.
func (uiq *UserInfoQuery) Offset(offset int) *UserInfoQuery {
	uiq.offset = &offset
	return uiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uiq *UserInfoQuery) Unique(unique bool) *UserInfoQuery {
	uiq.unique = &unique
	return uiq
}

// Order adds an order step to the query.
func (uiq *UserInfoQuery) Order(o ...OrderFunc) *UserInfoQuery {
	uiq.order = append(uiq.order, o...)
	return uiq
}

// First returns the first UserInfo entity from the query.
// Returns a *NotFoundError when no UserInfo was found.
func (uiq *UserInfoQuery) First(ctx context.Context) (*UserInfo, error) {
	nodes, err := uiq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userinfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uiq *UserInfoQuery) FirstX(ctx context.Context) *UserInfo {
	node, err := uiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserInfo ID from the query.
// Returns a *NotFoundError when no UserInfo ID was found.
func (uiq *UserInfoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uiq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userinfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uiq *UserInfoQuery) FirstIDX(ctx context.Context) int {
	id, err := uiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserInfo entity is found.
// Returns a *NotFoundError when no UserInfo entities are found.
func (uiq *UserInfoQuery) Only(ctx context.Context) (*UserInfo, error) {
	nodes, err := uiq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userinfo.Label}
	default:
		return nil, &NotSingularError{userinfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uiq *UserInfoQuery) OnlyX(ctx context.Context) *UserInfo {
	node, err := uiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserInfo ID in the query.
// Returns a *NotSingularError when more than one UserInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (uiq *UserInfoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uiq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userinfo.Label}
	default:
		err = &NotSingularError{userinfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uiq *UserInfoQuery) OnlyIDX(ctx context.Context) int {
	id, err := uiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserInfos.
func (uiq *UserInfoQuery) All(ctx context.Context) ([]*UserInfo, error) {
	if err := uiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return uiq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (uiq *UserInfoQuery) AllX(ctx context.Context) []*UserInfo {
	nodes, err := uiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserInfo IDs.
func (uiq *UserInfoQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := uiq.Select(userinfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uiq *UserInfoQuery) IDsX(ctx context.Context) []int {
	ids, err := uiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uiq *UserInfoQuery) Count(ctx context.Context) (int, error) {
	if err := uiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return uiq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (uiq *UserInfoQuery) CountX(ctx context.Context) int {
	count, err := uiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uiq *UserInfoQuery) Exist(ctx context.Context) (bool, error) {
	if err := uiq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return uiq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (uiq *UserInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := uiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uiq *UserInfoQuery) Clone() *UserInfoQuery {
	if uiq == nil {
		return nil
	}
	return &UserInfoQuery{
		config:     uiq.config,
		limit:      uiq.limit,
		offset:     uiq.offset,
		order:      append([]OrderFunc{}, uiq.order...),
		predicates: append([]predicate.UserInfo{}, uiq.predicates...),
		// clone intermediate query.
		sql:    uiq.sql.Clone(),
		path:   uiq.path,
		unique: uiq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserInfo.Query().
//		GroupBy(userinfo.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uiq *UserInfoQuery) GroupBy(field string, fields ...string) *UserInfoGroupBy {
	grbuild := &UserInfoGroupBy{config: uiq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := uiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return uiq.sqlQuery(ctx), nil
	}
	grbuild.label = userinfo.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.UserInfo.Query().
//		Select(userinfo.FieldCreatedAt).
//		Scan(ctx, &v)
func (uiq *UserInfoQuery) Select(fields ...string) *UserInfoSelect {
	uiq.fields = append(uiq.fields, fields...)
	selbuild := &UserInfoSelect{UserInfoQuery: uiq}
	selbuild.label = userinfo.Label
	selbuild.flds, selbuild.scan = &uiq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a UserInfoSelect configured with the given aggregations.
func (uiq *UserInfoQuery) Aggregate(fns ...AggregateFunc) *UserInfoSelect {
	return uiq.Select().Aggregate(fns...)
}

func (uiq *UserInfoQuery) prepareQuery(ctx context.Context) error {
	for _, f := range uiq.fields {
		if !userinfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uiq.path != nil {
		prev, err := uiq.path(ctx)
		if err != nil {
			return err
		}
		uiq.sql = prev
	}
	return nil
}

func (uiq *UserInfoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserInfo, error) {
	var (
		nodes = []*UserInfo{}
		_spec = uiq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserInfo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserInfo{config: uiq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uiq *UserInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uiq.querySpec()
	_spec.Node.Columns = uiq.fields
	if len(uiq.fields) > 0 {
		_spec.Unique = uiq.unique != nil && *uiq.unique
	}
	return sqlgraph.CountNodes(ctx, uiq.driver, _spec)
}

func (uiq *UserInfoQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := uiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (uiq *UserInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userinfo.Table,
			Columns: userinfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userinfo.FieldID,
			},
		},
		From:   uiq.sql,
		Unique: true,
	}
	if unique := uiq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := uiq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userinfo.FieldID)
		for i := range fields {
			if fields[i] != userinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uiq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uiq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uiq *UserInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uiq.driver.Dialect())
	t1 := builder.Table(userinfo.Table)
	columns := uiq.fields
	if len(columns) == 0 {
		columns = userinfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uiq.sql != nil {
		selector = uiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uiq.unique != nil && *uiq.unique {
		selector.Distinct()
	}
	for _, p := range uiq.predicates {
		p(selector)
	}
	for _, p := range uiq.order {
		p(selector)
	}
	if offset := uiq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uiq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserInfoGroupBy is the group-by builder for UserInfo entities.
type UserInfoGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uigb *UserInfoGroupBy) Aggregate(fns ...AggregateFunc) *UserInfoGroupBy {
	uigb.fns = append(uigb.fns, fns...)
	return uigb
}

// Scan applies the group-by query and scans the result into the given value.
func (uigb *UserInfoGroupBy) Scan(ctx context.Context, v any) error {
	query, err := uigb.path(ctx)
	if err != nil {
		return err
	}
	uigb.sql = query
	return uigb.sqlScan(ctx, v)
}

func (uigb *UserInfoGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range uigb.fields {
		if !userinfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := uigb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uigb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (uigb *UserInfoGroupBy) sqlQuery() *sql.Selector {
	selector := uigb.sql.Select()
	aggregation := make([]string, 0, len(uigb.fns))
	for _, fn := range uigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(uigb.fields)+len(uigb.fns))
		for _, f := range uigb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(uigb.fields...)...)
}

// UserInfoSelect is the builder for selecting fields of UserInfo entities.
type UserInfoSelect struct {
	*UserInfoQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uis *UserInfoSelect) Aggregate(fns ...AggregateFunc) *UserInfoSelect {
	uis.fns = append(uis.fns, fns...)
	return uis
}

// Scan applies the selector query and scans the result into the given value.
func (uis *UserInfoSelect) Scan(ctx context.Context, v any) error {
	if err := uis.prepareQuery(ctx); err != nil {
		return err
	}
	uis.sql = uis.UserInfoQuery.sqlQuery(ctx)
	return uis.sqlScan(ctx, v)
}

func (uis *UserInfoSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(uis.fns))
	for _, fn := range uis.fns {
		aggregation = append(aggregation, fn(uis.sql))
	}
	switch n := len(*uis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		uis.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		uis.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := uis.sql.Query()
	if err := uis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
