// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeInt64, Unique: true},
		{Name: "name", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(20)"}},
		{Name: "email", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"mysql": "varchar(255)"}},
		{Name: "password", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(255)"}},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{UserColumns[3]},
			},
		},
	}
	// UserInfoColumns holds the columns for the "user_info" table.
	UserInfoColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeInt64, Unique: true},
		{Name: "sex", Type: field.TypeInt8, Default: 0},
		{Name: "age", Type: field.TypeInt8, Nullable: true},
		{Name: "birthday", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "date"}},
		{Name: "motto", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "varchar(255)"}},
	}
	// UserInfoTable holds the schema information for the "user_info" table.
	UserInfoTable = &schema.Table{
		Name:       "user_info",
		Columns:    UserInfoColumns,
		PrimaryKey: []*schema.Column{UserInfoColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{UserInfoColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UserTable,
		UserInfoTable,
	}
)

func init() {
	UserTable.Annotation = &entsql.Annotation{
		Table: "user",
	}
	UserInfoTable.Annotation = &entsql.Annotation{
		Table: "user_info",
	}
}
